{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bgg-inventory-nextjs.fullname" . }}-{{ .Values.persistence.volumeName }}
spec:
  accessModes: {{ toJson .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
{{- end }}

{{- if .Values.persistenceAllgames.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bgg-inventory-nextjs.fullname" . }}-{{ .Values.persistenceAllgames.volumeName }}
spec:
  accessModes: {{ toJson .Values.persistenceAllgames.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistenceAllgames.size }}
  storageClassName: {{ .Values.persistenceAllgames.storageClassName | quote }}
{{- end }}